# Generated by Django 6.0 on 2025-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(default='padrao', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tempo_de_servico',
            field=models.IntegerField(default=0),
        ),
    ]
